### ISSUE TITLE
watchOS by Tutorials

### ISSUE THREAD

**Issue by EtherTyper** [raywenderlich/rw-deprecated-books#1]
Will _watchOS by Tutorials_ ever be made available here? It's currently not available for purchase, but also not on this list.

**Comment by EtherTyper** [comment]
Also, will _Mastering Git_ be made available here?

**Comment by mvolpato** [comment]
Wow, mastering git becoming deprecated. I don't see that happening soon.

**Comment by EtherTyper** [comment]
@mvolpato It already has happened. https://github.com/raywenderlich/git-materials

**Comment by jellodiil** [comment]
Hey @EtherTyper ! 
We are in the process of writing a new watchOS book at the moment, so once that is out, we will probably have decision about what will happen to the now rather old watchOS by Tutorials book. 

And we split Mastering Git into two books (Git Apprentice and Advanced Git) by skill level; each of the new books is half of the old book. That was so we could give basic Git information to beginners, and not overwhelm them with the more advanced stuff we put in the Pro version. So, Mastering Git won't be available here.
