### ISSUE TITLE
tvOS Apprentice Chapter 28

### ISSUE THREAD

**Issue by EtherTyper** [raywenderlich/rw-deprecated-books#2]
The tvOS Apprentice version included in this repository doesn't seem to include chapter 28.

> https://www.raywenderlich.com/1345-announcing-the-tvos-apprentice-week#toc-anchor-007

> Chapter 28, Server Deployment: Similarly, developing TVML apps for tvOS requires some knowledge for being able to deploy servers. We have a crash course on that for you too. :]

**Comment by jellodiil** [comment]
@EtherTyper 
Hey! We have only linked the newest version of each book in this repo, for tvOS Apprentice that is v3. 
It looks like Chapter 28 was cut for some reason in later versions :(
[https://www.raywenderlich.com/373-tvos-apprentice-updated-for-swift-4-and-tvos-11](https://www.raywenderlich.com/373-tvos-apprentice-updated-for-swift-4-and-tvos-11)


However, if you specifically need Chapter 28, I've linked the zip for the 1st edition [here](https://cdn.raywenderlich.com/deprecated-books/tvt/tvOS_Apprentice_v1.1.zip).
